name: Performance benchmark
on:
  schedule:
    - cron:  '30 17 * * *'
  workflow_dispatch:


jobs:
  benchmark:
    name: Performance regression check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install Pip package manager
        run: python -m pip install --upgrade pip
      - name: Install Python dependencies via Pip
        run: pip install -r requirements/requirements310.txt
      - name: Decrypt Autumn secrets
        run: python -m autumn secrets read
        env:
          AUTUMN_PASSWORD: ${{ secrets.AUTUMN_PASSWORD }}
      - name: Run benchmark tests
        run: pytest -W ignore -vv -m benchmark --benchmark-json benchmark.json
      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          tool: "pytest"
          output-file-path: benchmark.json
          github-token: ${{ secrets.PAGES_GITHUB_TOKEN }}
          gh-pages-branch: benchmark-page
          benchmark-data-dir-path: "."
          auto-push: true
